"""AUTO-GENERATED by code/symbolic/derive_junction.py -- do not edit.
Linear junction system A x = B (Psi_-, dPsi_-/dr), unknowns:
  chi_a, Pp, dPp
rows: [h_tA], [h_AB], Israel_tA, Israel_AB
T = last two rows of A^+ B (least squares if overdetermined)."""
import numpy as np
from numpy import sqrt, pi, exp

I = 1j


def A(omega, lam, R, M, v_s2):
    return np.array([[1j*R**(5/2)*omega/sqrt(-2*M + R), (1/2)*sqrt(-2*M + R)/sqrt(R), (1/2)*sqrt(R)*sqrt(-2*M + R)],
        [-2*R**2, 0, 0],
        [(-4*1j*M*R**(11/2)*omega + 3*1j*M*R**5*omega*sqrt(-2*M + R) + 2*1j*R**(13/2)*omega - 2*1j*R**6*omega*sqrt(-2*M + R))/(-2*M*R**(9/2) + 2*M*R**4*sqrt(-2*M + R) + R**(11/2) - R**5*sqrt(-2*M + R)), (16*M**2*R**(5/2) - 12*M**2*R**2*sqrt(-2*M + R) - 2*M*R**(7/2)*lam - 12*M*R**(7/2) + 2*M*R**3*lam*sqrt(-2*M + R) + 10*M*R**3*sqrt(-2*M + R) + R**(9/2)*lam + 2*R**(9/2) - R**4*lam*sqrt(-2*M + R) - 2*R**4*sqrt(-2*M + R))/(-8*M*R**(9/2) + 8*M*R**4*sqrt(-2*M + R) + 4*R**(11/2) - 4*R**5*sqrt(-2*M + R)), (8*M**2*R**(7/2) - 6*M**2*R**3*sqrt(-2*M + R) - 8*M*R**(9/2) + 7*M*R**4*sqrt(-2*M + R) + 2*R**(11/2) - 2*R**5*sqrt(-2*M + R))/(-4*M*R**(9/2) + 4*M*R**4*sqrt(-2*M + R) + 2*R**(11/2) - 2*R**5*sqrt(-2*M + R))],
        [(-6*M*R**(5/2)*sqrt(-2*M + R) + 8*M*R**3 + 4*R**(7/2)*sqrt(-2*M + R) - 4*R**4)/(2*M*R**2 + R**(5/2)*sqrt(-2*M + R) - R**3), (-1j*R**(7/2)*omega*sqrt(-2*M + R) + 1j*R**4*omega)/(4*M*R**2 + 2*R**(5/2)*sqrt(-2*M + R) - 2*R**3), 0]], dtype=complex)

def B(omega, lam, R, M, v_s2):
    return np.array([[1/2, (1/2)*R],
        [0, 0],
        [(-12*M**2*R**(5/2) - 2*M*R**(7/2)*lam + 18*M*R**(7/2) + 2*M*R**3*lam*sqrt(-2*M + R) - 12*M*R**3*sqrt(-2*M + R) + R**(9/2)*lam - 6*R**(9/2) - R**4*lam*sqrt(-2*M + R) + 6*R**4*sqrt(-2*M + R))/(-8*M*R**(9/2) + 8*M*R**4*sqrt(-2*M + R) + 4*R**(11/2) - 4*R**5*sqrt(-2*M + R)), (-6*M**2*R**(7/2) + 7*M*R**(9/2) - 4*M*R**4*sqrt(-2*M + R) - 2*R**(11/2) + 2*R**5*sqrt(-2*M + R))/(-4*M*R**(9/2) + 4*M*R**4*sqrt(-2*M + R) + 2*R**(11/2) - 2*R**5*sqrt(-2*M + R))],
        [(-1j*R**(7/2)*omega*sqrt(-2*M + R) + 1j*R**4*omega)/(4*M*R**2 + 2*R**(5/2)*sqrt(-2*M + R) - 2*R**3), 0]], dtype=complex)

def T(omega, lam, R, M=1.0, v_s2=0.0):
    a = A(omega, lam, R, M, v_s2)
    b = B(omega, lam, R, M, v_s2)
    X = np.linalg.lstsq(a, b, rcond=None)[0]
    return X[-2:, :]

def residual(omega, lam, R, M=1.0, v_s2=0.0):
    a = A(omega, lam, R, M, v_s2); b = B(omega, lam, R, M, v_s2)
    X = np.linalg.lstsq(a, b, rcond=None)[0]
    return np.abs(a @ X - b).max() / np.abs(b).max()

