"""AUTO-GENERATED by code/symbolic/derive_junction.py -- do not edit.
Linear junction system A x = B (Psi_-, dPsi_-/dr), unknowns:
  chi_a, U, Pp, dPp
rows: [h_tA], [h_AB], Israel_tA, Israel_AB
T = last two rows of A^+ B (least squares if overdetermined)."""
import numpy as np
from numpy import sqrt, pi, exp

I = 1j


def A(omega, lam, R, M, v_s2):
    return np.array([[1j*R**(5/2)*omega/sqrt(-2*M + R), 0, (1/2)*sqrt(-2*M + R)/sqrt(R), (1/2)*sqrt(R)*sqrt(-2*M + R)],
        [-2*R**2, 0, 0, 0],
        [1j*R**(3/2)*omega*sqrt(-2*M + R)/(2*M - R), (-6*M**2*R**4 - 2*M*R**(9/2)*sqrt(-2*M + R) + 5*M*R**5 + R**(11/2)*sqrt(-2*M + R) - R**6)/(2*M*R**(11/2)*sqrt(-2*M + R) - R**(13/2)*sqrt(-2*M + R)), (8*M**2*R**4 + 2*M*R**(9/2)*lam*sqrt(-2*M + R) - 4*M*R**(9/2)*sqrt(-2*M + R) - 8*M*R**5 - R**(11/2)*lam*sqrt(-2*M + R) + 2*R**(11/2)*sqrt(-2*M + R) + 2*R**6)/(8*M*R**(11/2)*sqrt(-2*M + R) - 4*R**(13/2)*sqrt(-2*M + R)), (4*M**2 - 4*M*R + R**2)/(4*M*sqrt(R)*sqrt(-2*M + R) - 2*R**(3/2)*sqrt(-2*M + R))],
        [2*R, 0, (1/2)*1j*R**(3/2)*omega/sqrt(-2*M + R), 0]], dtype=complex)

def B(omega, lam, R, M, v_s2):
    return np.array([[1/2, (1/2)*R],
        [0, 0],
        [(1/4)*(lam - 4)/R, -1/2],
        [(1/2)*1j*R**(3/2)*omega/sqrt(-2*M + R), 0]], dtype=complex)

def T(omega, lam, R, M=1.0, v_s2=0.0):
    a = A(omega, lam, R, M, v_s2)
    b = B(omega, lam, R, M, v_s2)
    X = np.linalg.lstsq(a, b, rcond=None)[0]
    return X[-2:, :]

def residual(omega, lam, R, M=1.0, v_s2=0.0):
    a = A(omega, lam, R, M, v_s2); b = B(omega, lam, R, M, v_s2)
    X = np.linalg.lstsq(a, b, rcond=None)[0]
    return np.abs(a @ X - b).max() / np.abs(b).max()

